name: "Continue Base Review"
description: "Zero-config AI code review - just add this action and optionally an API key"
author: "Continue Dev, Inc."

inputs:
  continue-api-key:
    description: "API key for Continue service (required)"
    required: true
  use_github_app:
    description: "Use GitHub App for bot identity (defaults to true)"
    default: "true"
    required: false
  app-id:
    description: "GitHub App ID (optional, defaults to Continue Agent app)"
    required: false
    default: "1090372"  # Continue Agent App ID
  app-private-key:
    description: "GitHub App Private Key (optional, defaults to repository secret)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check trigger
      id: check
      shell: bash
      run: |
        # Determine if we should run based on event type
        SHOULD_RUN="false"
        REVIEW_TYPE="general"
        
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          if [ "${{ github.event.pull_request.draft }}" != "true" ]; then
            SHOULD_RUN="true"
          fi
        elif [ "${{ github.event_name }}" = "issue_comment" ]; then
          if [ "${{ github.event.issue.pull_request }}" != "" ]; then
            COMMENT="${{ github.event.comment.body }}"
            # Check for @continue-agent mention
            if echo "$COMMENT" | grep -qi "@continue-agent"; then
              SHOULD_RUN="true"
              # Check for review type keywords
              if echo "$COMMENT" | grep -qi "detailed"; then
                REVIEW_TYPE="detailed"
              fi
            fi
          fi
        fi
        
        echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT
        echo "review_type=$REVIEW_TYPE" >> $GITHUB_OUTPUT
        
        # Debug output
        echo "Event: ${{ github.event_name }}"
        echo "Should run: $SHOULD_RUN"
        echo "Review type: $REVIEW_TYPE"

    - name: Generate GitHub App Token
      if: steps.check.outputs.should_run == 'true' && inputs.use_github_app == 'true'
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id || secrets.CONTINUE_APP_ID || '1090372' }}
        private-key: ${{ inputs.app-private-key || secrets.CONTINUE_APP_PRIVATE_KEY }}
      continue-on-error: true

    - name: Comment on App Installation
      if: steps.check.outputs.should_run == 'true' && inputs.use_github_app == 'true' && steps.app-token.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const prNumber = context.payload.pull_request?.number || context.payload.issue?.number;
          if (prNumber) {
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 Continue Agent Setup\n\nI noticed the Continue Agent GitHub App isn't installed on this repository.\n\n**To enable AI-powered code reviews with proper bot identity:**\n\n1. 📱 [Install the Continue Agent app](https://github.com/apps/continue-agent)\n2. ✅ Grant it access to this repository\n3. 🔄 Re-run this workflow or comment \`@continue-agent\` to trigger a new review\n\n**Benefits of using the app:**\n- Reviews appear from the Continue Agent bot instead of github-actions\n- Better formatting and threading of review comments\n- Enhanced permissions for code analysis\n\n*Note: Reviews will still work without the app, but with limited features.*`
            });
          }

    - name: Run Continue Detailed Review  
      if: steps.check.outputs.should_run == 'true'
      uses: continuedev/continue/actions/detailed-review@bdougie/continue-agent
      with:
        continue-api-key: ${{ inputs.continue-api-key }}
        continue-org: "continuedev"
        continue-config: "continuedev/review-bot"
        use_github_app: ${{ inputs.use_github_app }}
        app-id: ${{ inputs.app-id }}
        app-private-key: ${{ inputs.app-private-key }}
        github-token: ${{ steps.app-token.outputs.token || github.token }}

branding:
  icon: "code"
  color: "blue"
