name: "Continue Base Review"
description: "Zero-config AI code review - just add this action and optionally an API key"
author: "Continue Dev, Inc."

inputs:
  continue-api-key:
    description: "API key for Continue service (required)"
    required: true
  app-id:
    description: "GitHub App ID (optional, defaults to Continue's app)"
    required: false
    default: "1090372"  # Continue Agent App ID
  app-private-key:
    description: "GitHub App Private Key (optional, defaults to Continue's app)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check trigger
      id: check
      shell: bash
      run: |
        # Determine if we should run based on event type
        SHOULD_RUN="false"
        REVIEW_TYPE="general"
        
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          if [ "${{ github.event.pull_request.draft }}" != "true" ]; then
            SHOULD_RUN="true"
          fi
        elif [ "${{ github.event_name }}" = "issue_comment" ]; then
          if [ "${{ github.event.issue.pull_request }}" != "" ]; then
            COMMENT="${{ github.event.comment.body }}"
            # Check for @continue-agent mention
            if echo "$COMMENT" | grep -qi "@continue-agent"; then
              SHOULD_RUN="true"
              # Check for review type keywords
              if echo "$COMMENT" | grep -qi "detailed"; then
                REVIEW_TYPE="detailed"
              fi
            fi
          fi
        fi
        
        echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT
        echo "review_type=$REVIEW_TYPE" >> $GITHUB_OUTPUT
        
        # Debug output
        echo "Event: ${{ github.event_name }}"
        echo "Should run: $SHOULD_RUN"
        echo "Review type: $REVIEW_TYPE"

    - name: Generate GitHub App Token
      if: steps.check.outputs.should_run == 'true' && inputs.app-private-key != ''
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-private-key }}

    - name: Run Continue Review
      if: steps.check.outputs.should_run == 'true'
      uses: continuedev/continue/actions/general-review@bdougie/continue-agent
      with:
        continue-api-key: ${{ inputs.continue-api-key }}
        continue-org: "continue"
        continue-config: "continue/default"
        github-token: ${{ steps.app-token.outputs.token || github.token }}

branding:
  icon: "code"
  color: "blue"
