# Simple redirects for documentation restructuring

# Core feature redirects
[[redirects]]
  from = "/chat/how-to-use-it"
  to = "/features/chat/quick-start"
  status = 301

[[redirects]]
  from = "/autocomplete/how-to-use-it"
  to = "/features/autocomplete/quick-start"
  status = 301

[[redirects]]
  from = "/edit/how-to-use-it"
  to = "/features/edit/quick-start"
  status = 301

[[redirects]]
  from = "/agent/how-to-use-it"
  to = "/features/agent/quick-start"
  status = 301

# Top-level redirects
[[redirects]]
  from = "/reference"
  to = "/advanced/reference"
  status = 301

[[redirects]]
  from = "/troubleshooting"
  to = "/advanced/troubleshooting"
  status = 301