name: Continue Detailed Review

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  detailed-code-review:
    name: Continue Detailed Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v2.0.0
        with:
          app-id: ${{ secrets.CONTINUE_APP_ID }}
          private-key: ${{ secrets.CONTINUE_APP_PRIVATE_KEY }}

      - name: Run Detailed PR Review
        uses: continuedev/continue/actions/detailed-review@b3f4b82600f603ca28c65a319b80ec36c4644ed7
        with:
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          continue-org: continuedev
          continue-config: continuedev/review-bot
          github-token: ${{ steps.app-token.outputs.token }}
