name: 'E2E Tests'
description: 'Reusable workflow for running VS Code E2E tests'

on:
  workflow_call:
    inputs:
      is_fork:
        description: 'Whether this is running on a fork'
        type: boolean
        default: false
    secrets:
      CI_GITHUB_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
      GH_ACTIONS_SSH_TEST_KEY_PEM:
        required: false
      GH_ACTIONS_SSH_TEST_DNS_NAME:
        required: false

jobs:
  vscode-get-test-file-matrix:
    runs-on: ubuntu-latest
    outputs:
      test_file_matrix: ${{ steps.get-matrix.outputs.test_file_matrix }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get test matrix
        id: get-matrix
        uses: ./.github/actions/run-vscode-e2e-tests
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ci-github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          is_fork: ${{ inputs.is_fork }}

  vscode-e2e-tests:
    name: ${{ matrix.test_file || 'unknown' }} (${{ matrix.command }})
    needs: [vscode-get-test-file-matrix]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        test_file: ${{ fromJson(needs.vscode-get-test-file-matrix.outputs.test_file_matrix) }}
        command: ["e2e:ci:run", "e2e:ci:run-yaml"]
    steps:
      - uses: actions/checkout@v5
      - name: Run VS Code E2E test
        uses: ./.github/actions/run-vscode-e2e-test
        with:
          test_file: ${{ matrix.test_file }}
          command: ${{ matrix.command }}
          ssh_key: ${{ secrets.GH_ACTIONS_SSH_TEST_KEY_PEM }}
          ssh_host: ${{ secrets.GH_ACTIONS_SSH_TEST_DNS_NAME }}
          is_fork: ${{ inputs.is_fork }}